Updated bin crunch files.

diff --git a/bin/bash_completion b/bin/bash_completion
--- a/bin/bash_completion
+++ b/bin/bash_completion
@@ -4,9 +4,10 @@ _crunch()
     local cur
     cur=${COMP_WORDS[COMP_CWORD]}
     #prev=${COMP_WORDS[COMP_CWORD-1]}
+
     case ${COMP_CWORD} in
         1)
-            COMPREPLY=($(compgen -W "--modules_dir cancel monitor requeue reset submit template" -- ${cur}))
+            COMPREPLY=($(compgen -W "--modules-dir cancel monitor requeue reset submit template test" -- ${cur}))
             ;;
         #2)
         #    case ${prev} in
@@ -18,84 +19,87 @@ _crunch()
         #            ;;
         #    esac
         #    ;;
-        2)
-            if [[ "${COMP_WORDS[COMP_CWORD-1]}" != "--modules_dir" ]]
-            then
-                modules_dir=$(pwd -P)
-
-                startpath=$(cd ${modules_dir} && pwd -P)
-                branches=$(find ${startpath} -path '*/.*' -prune -o -type d -exec bash -c 'echo "$(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g" | grep -o / | wc -l) $(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g")"' \; | grep -v '/jobs/' | sort -u | tr '\n' ',')
-                maxdepth=$(echo ${branches} | tr ',' '\n' | cut -d' ' -f1 | sort -u | tail -n1)
-                leaves=$(echo ${branches} | tr ',' '\n' | grep "^${maxdepth} " | cut -d' ' -f2 | tr '\n' ',')
-                moddirpath=$(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1,2 --complement | rev | head -n1)
-                #modnames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f2 | rev))
-                #controllernames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1 | rev))
-
-                modcontrollernames=$(find ${moddirpath} -mindepth 1 -path '*/.*' -prune -o -type d -regextype posix-extended -regex ".*/${cur}.*" -print 2>/dev/null | grep -v '/jobs' | rev | cut -d'/' -f1 | rev)
-                
-                COMPREPLY=($(compgen -W "${modcontrollernames}" -- ${cur}))
-            fi
-            ;;
-        3)
-            if [[ "${COMP_WORDS[COMP_CWORD-2]}" != "--modules_dir" ]]
-            then
-                modules_dir=$(pwd -P)
-
-                startpath=$(cd ${modules_dir} && pwd -P)
-                branches=$(find ${startpath} -path '*/.*' -prune -o -type d -exec bash -c 'echo "$(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g" | grep -o / | wc -l) $(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g")"' \; | grep -v '/jobs/' | sort -u | tr '\n' ',')
-                maxdepth=$(echo ${branches} | tr ',' '\n' | cut -d' ' -f1 | sort -u | tail -n1)
-                leaves=$(echo ${branches} | tr ',' '\n' | grep "^${maxdepth} " | cut -d' ' -f2 | tr '\n' ',')
-                moddirpath=$(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1,2 --complement | rev | head -n1)
-
-                modpath="${moddirpath}/${COMP_WORDS[COMP_CWORD-1]}"
-
-                modnames=""
-                controllernames=$(find ${modpath} -mindepth 1 -maxdepth 1 -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev)
-
-                COMPREPLY=($(compgen -W "${modnames} ${controllernames}" -- ${cur}))
-            else
-                COMPREPLY=($(compgen -W "cancel monitor requeue reset submit template" -- ${cur}))
-            fi            
-            ;;
-        4)
-            if [[ "${COMP_WORDS[COMP_CWORD-3]}" == "--modules_dir" ]]
-            then
-                modules_dir=$(eval echo ${COMP_WORDS[COMP_CWORD-2]})
-
-                startpath=$(cd ${modules_dir} && pwd -P)
-                branches=$(find ${startpath} -path '*/.*' -prune -o -type d -exec bash -c 'echo "$(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g" | grep -o / | wc -l) $(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g")"' \; | grep -v '/jobs/' | sort -u | tr '\n' ',')
-                maxdepth=$(echo ${branches} | tr ',' '\n' | cut -d' ' -f1 | sort -u | tail -n1)
-                leaves=$(echo ${branches} | tr ',' '\n' | grep "^${maxdepth} " | cut -d' ' -f2 | tr '\n' ',')
-                moddirpath=$(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1,2 --complement | rev | head -n1)
-                #modnames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f2 | rev))
-                #controllernames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1 | rev))
-
-                modcontrollernames=$(find ${moddirpath} -mindepth 1 -path '*/.*' -prune -o -type d -regextype posix-extended -regex ".*/${cur}.*" -print 2>/dev/null | grep -v '/jobs' | rev | cut -d'/' -f1 | rev)
-                
-                COMPREPLY=($(compgen -W "${modcontrollernames}" -- ${cur}))
-            fi
-            ;;
-        5)
-            if [[ "${COMP_WORDS[COMP_CWORD-4]}" == "--modules_dir" ]]
-            then
-                modules_dir=$(eval echo ${COMP_WORDS[COMP_CWORD-3]})
-
-                startpath=$(cd ${modules_dir} && pwd -P)
-                branches=$(find ${startpath} -path '*/.*' -prune -o -type d -exec bash -c 'echo "$(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g" | grep -o / | wc -l) $(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g")"' \; | grep -v '/jobs/' | sort -u | tr '\n' ',')
-                maxdepth=$(echo ${branches} | tr ',' '\n' | cut -d' ' -f1 | sort -u | tail -n1)
-                leaves=$(echo ${branches} | tr ',' '\n' | grep "^${maxdepth} " | cut -d' ' -f2 | tr '\n' ',')
-                moddirpath=$(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1,2 --complement | rev | head -n1)
-
-                modpath="${moddirpath}/${COMP_WORDS[COMP_CWORD-1]}"
-
-                modnames=""
-                controllernames=$(find ${modpath} -mindepth 1 -maxdepth 1 -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev)
-
-                COMPREPLY=($(compgen -W "${modnames} ${controllernames}" -- ${cur}))
-            fi
-            ;;
         *)
-            COMPREPLY=()
+            case ${COMP_WORDS[1]} in
+                --modules_dir)
+                    modules_dir=$(eval echo ${COMP_WORDS[COMP_CWORD-2]})
+                    right_shift=2
+                    ;;
+                *)
+                    modules_dir=$(pwd -P)
+                    right_shift=0
+                    ;;
+            esac
+
+            startpath=$(cd ${modules_dir} && pwd -P)
+
+            currdir=${startpath}
+
+            module_paths=($(find ${currdir} -mindepth 1 -type d -path '*/.*' -prune -o -type f -name '.DBCrunch' -execdir pwd -P \;))
+
+            currdir=$(cd ${currdir}/.. && pwd -P)
+            dirstats=$(stat -c '%a %U' ${currdir})
+            while [[ "${dirstats}" =~ ^"777 " ]] || [[ "${dirstats}" =~ " ${USER}"$ ]]
+            do
+                if [ -f "${currdir}/.DBCrunch" ]
+                then
+                    module_paths=("${currdir}" "${module_paths[@]}")
+                fi
+                currdir=$(cd ${currdir}/.. && pwd -P)
+                dirstats=$(stat -c '%a %U' ${currdir})
+            done
+
+            if [ "${#module_paths[@]}" -eq 0 ]
+            then
+                echo "Error: No module path detected."
+                exit 1
+            elif [ "${#module_paths[@]}" -gt 1 ]
+            then
+                echo "Error: Multiple module paths detected. Please choose one:"
+                for i in ${!module_paths[@]}
+                do
+                    echo "  ${i}) ${module_paths[${i}]}"
+                done
+                exit 1
+            fi
+
+            moddirpath=${module_paths[0]}
+
+            case ${COMP_CWORD} in
+                $((1+${right_shift})) )
+                    COMPREPLY=($(compgen -W "cancel monitor requeue reset submit template test" -- ${cur}))
+                    ;;
+                *)
+                    case ${COMP_WORDS[1+right_shift]} in
+                        test)
+                            right_shift=$((${right_shift}+1))
+                            ;;
+                    esac
+                            
+                    case ${COMP_CWORD} in
+                        $((1+${right_shift})) )
+                            COMPREPLY=($(compgen -W "true false" -- ${cur}))
+                            ;;
+                        $((2+${right_shift})) )
+                            modcontrollernames=$(find ${moddirpath} -mindepth 1 -type d -path '*/.*' -prune -o -type d -regextype posix-extended -regex ".*/${cur}.*" -print 2>/dev/null | grep -v '/jobs' | rev | cut -d'/' -f1 | rev)
+            
+                            COMPREPLY=($(compgen -W "${modcontrollernames}" -- ${cur}))
+                            ;;
+                        $((3+${right_shift})) )
+                            modpath="${moddirpath}/${COMP_WORDS[COMP_CWORD-1]}"
+
+                            modnames=""
+                            controllernames=$(find ${modpath} -mindepth 1 -maxdepth 1 -type d -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev)
+
+                            COMPREPLY=($(compgen -W "${modnames} ${controllernames}" -- ${cur}))
+                            ;;
+                        *)
+                            COMPREPLY=()
+                            ;;
+                    esac
+                    ;;
+
+            esac
             ;;
     esac
 }
diff --git a/bin/crunch b/bin/crunch
--- a/bin/crunch
+++ b/bin/crunch
@@ -1,44 +1,188 @@
 #!/bin/bash
 
-do_crunch () {
-    modpath=$1
-    controllerpath=$2
-    workpath=$3
+do_create() {
+    is_create=$1
+    path=$2
 
-    jobs=$(find ${controllerpath} -path '*/.*' -prune -o -type f -name "*.job" -print 2>/dev/null)
-    for job in ${jobs}
-    do
-        jobname=$(echo ${job} | rev | cut -d'/' -f1 | rev)
-        jobmsg=$(sbatch ${job} 2>&1)
-        echo "${jobmsg} as ${jobname}."
-    done
+    if ${is_create}
+    then
+        mkdir ${path}
+    fi
 }
 
-do_not_dir() {
-    path=$1
+run_subcommand() {
+    scriptpath=$1
+    shift
+
+    is_create=$1
+    shift
+
+    modules_dir=$1
+    shift
+
+    startpath=$(cd ${modules_dir} && pwd -P)
+
+    currdir=${startpath}
+
+    module_paths=($(find ${currdir} -mindepth 1 -type d -path '*/.*' -prune -o -type f -name '.DBCrunch' -execdir pwd -P \;))
+
+    currdir=$(cd ${currdir}/.. && pwd -P)
+    dirstats=$(stat -c '%a %U' ${currdir})
+    while [[ "${dirstats}" =~ ^"777 " ]] || [[ "${dirstats}" =~ " ${USER}"$ ]]
+    do
+        if [ -f "${currdir}/.DBCrunch" ]
+        then
+            module_paths=("${currdir}" "${module_paths[@]}")
+        fi
+        currdir=$(cd ${currdir}/.. && pwd -P)
+        dirstats=$(stat -c '%a %U' ${currdir})
+    done
+
+    if [ "${#module_paths[@]}" -eq 0 ]
+    then
+        echo "Error: No module path detected."
+        exit 1
+    elif [ "${#module_paths[@]}" -gt 1 ]
+    then
+        echo "Error: Multiple module paths detected. Please choose one:"
+        for i in ${!module_paths[@]}
+        do
+            echo "  ${i}) ${module_paths[${i}]}"
+        done
+        exit 1
+    fi
+
+    moddirpath=${module_paths[0]}
+    pathdiff=${startpath##${moddirpath}/}
+    if [[ "${pathdiff}" == "${startpath}" ]]
+    then
+        pathdiff=""
+    fi
+    read modname controllername <<< $(echo ${pathdiff} | sed 's/\// /g' | cut -d' ' -f1,2)
+
+    case $# in
+        0)
+            modnames=(${modname})
+            controllernames=(${controllername})
+            ;;
+        1)
+            case $1 in
+                ${modname} | ${controllername})
+                    modnames=(${modname})
+                    controllernames=(${controllername})
+                    ;;
+                *)
+                    if [ -d ${moddirpath}/${modname}/$1 ]
+                    then
+                        modnames=(${modname})
+                        controllernames=($1)
+                    elif [[ "${modname}" != "" ]]
+                    then
+                        if ${is_create}
+                        then
+                            modnames=(${modname})
+                            controllernames=($1)
+                        else
+                            modnames=($1)
+                            controllernames=()
+                        fi
+                    else
+                        modnames=($1)
+                        controllernames=()
+                    fi
+                    ;;
+            esac
+            ;;
+        2)
+            modnames=($1)
+            controllernames=($2)
+            ;;
+        *)
+            echo "Error: You must provide no more than 2 arguments. $# provided."
+            exit 1
+            ;;
+    esac
+
+    for i in ${!modnames[@]}
+    do
+        modname=${modnames[${i}]}
+
+        modpath="${moddirpath}/${modname}"
+
+        if [ ! -d "${modpath}" ] && ${is_create}
+        then
+            do_create ${is_create} ${modpath}
+        fi
+
+        if [[ "${controllernames[${i}]}" == "" ]]
+        then
+            controllernames=($(find ${modpath} -mindepth 1 -maxdepth 1 -type d -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev))
+
+            for controllername in ${controllernames[@]}
+            do
+                controllerpath="${modpath}/${controllername}"
+
+                if [ ! -d "${controllerpath}" ] && ${is_create}
+                then
+                    do_create ${is_create} ${controllerpath}
+                fi
+
+                workpath="${controllerpath}/jobs"
+
+                if [ ! -d "${workpath}" ] && ${is_create}
+                then
+                    do_create ${is_create} ${workpath}
+                fi
+
+                ${scriptpath} ${modpath} ${controllerpath} ${workpath}
+            done
+        else
+            controllername=${controllernames[${i}]}
+            controllerpath="${modpath}/${controllername}"
+
+            if [ ! -d "${controllerpath}" ] && ${is_create}
+            then
+                do_create ${is_create} ${controllerpath}
+            fi
+
+            workpath="${controllerpath}/jobs"
+
+            if [ ! -d "${workpath}" ] && ${is_create}
+            then
+                do_create ${is_create} ${workpath}
+            fi
+
+            ${scriptpath} ${modpath} ${controllerpath} ${workpath}
+        fi
+    done
 }
 
 ProgName=$(basename "${BASH_SOURCE[0]}")
 ProgDir=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd -P)
   
 sub_help(){
-    echo "Usage: $ProgName [<subcommand>] [options]\n"
-    echo "    crunch            Submit controller batch job in current directory"
+    echo "Usage: $ProgName [options] [<subcommand>] [module_name/controller_name] [controller_name]\n"
+    echo ""
+    echo "Options:"
+    echo "    crunch --modules-dir [<dir>]     Specify a working directory other than the current one"
+    echo ""
     echo "Subcommands:"
-    echo "    crunch cancel     Cancel module or controller jobs"
-    echo "    crunch monitor    Monitor all controller jobs"
-    echo "    crunch requeue    Requeue jobs skipped by controller"
-    echo "    crunch reset      Reset controller for a module"
-    echo "    crunch submit     Submit controller batch job"
-    echo "    crunch template   Create new controller for a module from a template"
+    echo "    crunch cancel                    Cancel module or controller jobs"
+    echo "    crunch monitor                   Monitor all controller jobs"
+    echo "    crunch requeue                   Requeue jobs skipped by controller"
+    echo "    crunch reset                     Reset controller for a module"
+    echo "    crunch submit                    Submit controller batch job"
+    echo "    crunch template                  Create new controller for a module from a template"
+    echo "    crunch test (true/false)         Test what modules and controllers are matched"
     echo ""
-    echo "For help with each subcommand run:"
-    echo "$ProgName <subcommand> -h|--help"
-    echo ""
+    #echo "For help with each subcommand run:"
+    #echo "$ProgName <subcommand> -h|--help"
+    #echo ""
 }
 
 sub_cancel(){
-    ${ProgDir}/cancel ${@}
+    is_create=false
+    run_subcommand ${ProgDir}/cancel ${is_create} ${@}
 }
 
 sub_monitor(){
@@ -51,23 +195,32 @@ sub_monitor(){
 }
 
 sub_requeue(){
-    ${ProgDir}/requeue ${@}
+    is_create=false
+    run_subcommand ${ProgDir}/requeue ${is_create} ${@}
 }
 
 sub_reset(){
-    ${ProgDir}/reset ${@}
+    is_create=false
+    run_subcommand ${ProgDir}/reset ${is_create} ${@}
 }
 
 sub_submit(){
-    ${ProgDir}/submit ${@}
+    is_create=false
+    run_subcommand ${ProgDir}/submit ${is_create} ${@}
 }
 
 sub_template(){
-    ${ProgDir}/template ${@}
+    is_create=false
+    run_subcommand ${ProgDir}/template ${is_create} ${@}
+}
+
+sub_test(){
+    is_create=$2
+    run_subcommand ${ProgDir}/test ${is_create} $1 ${@:3}
 }
 
 SHORTOPTS="m:" 
-LONGOPTS="modules_dir:" 
+LONGOPTS="modules-dir:" 
 
 ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS -- "$@" ) 
 
@@ -78,7 +231,7 @@ modules_dir=$(pwd -P)
 while true
 do
     case $1 in
-        -m | --modules_dir)
+        -m | --modules-dir)
             modules_dir=$2
             shift
             ;;
@@ -97,7 +250,7 @@ done
 if [ ! -d "${modules_dir}" ]
 then
     echo "Error: Directory \"${modules_dir}\" does not exist."
-    exit
+    exit 1
 fi
   
 subcommand=$1
@@ -105,143 +258,9 @@ case $subcommand in
     "-h" | "--help")
         sub_help
         ;;
-    "")
-        startpath=${modules_dir}
-        branches=$(find ${startpath} -path '*/.*' -prune -o -type d -exec bash -c 'echo "$(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g" | grep -o / | wc -l) $(echo '{}' 2>/dev/null | sed "s/\/jobs\$//g")"' \; | grep -v '/jobs/' | sort -u | tr '\n' ',')
-        maxdepth=$(echo ${branches} | tr ',' '\n' | cut -d' ' -f1 | sort -u | tail -n1)
-        leaves=$(echo ${branches} | tr ',' '\n' | grep "^${maxdepth} " | cut -d' ' -f2 | sed 's/\/jobs$//g' | tr '\n' ',')
-        moddirpath=$(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1,2 --complement | rev | head -n1)
-        modnames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f2 | rev))
-        controllernames=($(echo ${leaves} | tr ',' '\n' | rev | cut -d'/' -f1 | rev))
-
-        case $# in
-            0)
-                ;;
-            1)
-                if [[ "${moddirpath}" == "${startpath}" ]]
-                then
-                    modnames=($1)
-                    controllernames=()
-                else
-                    stopflag=false
-                    for i in ${!controllernames[@]}
-                    do
-                        if [[ "${controllernames[${i}]}" == "$1" ]]
-                        then
-                            modnames=(${modnames[${i}]})
-                            controllernames=(${controllernames[i]})
-                            stopflag=true
-                            break
-                        fi
-                    done
-                    if ! ${stopflag}
-                    then
-                        for modname in ${modnames[@]}
-                        do
-                            if [[ "${modname}" == "$1" ]]
-                            then
-                                modnames=(${modname})
-                                controllernames=()
-                                stopflag=true
-                                break
-                            fi
-                        done
-                    fi
-                    if ! ${stopflag}
-                    then
-                        for modname in $(find ${moddirpath} -mindepth 1 -maxdepth 1 -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev)
-                        do
-                            if [[ "${modname}" == "$1" ]]
-                            then
-                                modnames=(${modname})
-                                controllernames=()
-                                stopflag=true
-                                break
-                            fi
-                        done
-                    fi
-                    if ! ${stopflag}
-                    then
-                        for i in ${!modnames[@]}
-                        do
-                            modnames=(${modnames[${i}]})
-                            controllernames=($1)
-                        done
-                    fi
-                fi
-                ;;
-            2)
-                modnames=($1)
-                controllernames=($2)
-                ;;
-            *)
-                echo "Error: You must provide no more than 2 arguments. $# provided."
-                exit
-                ;;
-        esac
-
-        for i in ${!modnames[@]}
-        do
-            modname=${modnames[${i}]}
-
-            modpath="${moddirpath}/${modname}"
-
-            if [ ! -d "${modpath}" ]
-            then
-                do_not_dir ${modpath}
-            fi
-
-            if [[ "${controllernames[${i}]}" == "" ]]
-            then
-                controllernames=($(find ${modpath} -mindepth 1 -maxdepth 1 -path '*/.*' -prune -o -type d -print 2>/dev/null | rev | cut -d'/' -f1 | rev))
-
-                for controllername in ${controllernames[@]}
-                do
-                    controllerpath="${modpath}/${controllername}"
-
-                    if [ ! -d "${controllerpath}" ]
-                    then
-                        do_not_dir ${controllerpath}
-                    fi
-
-                    workpath="${controllerpath}/jobs"
-
-                    if [ ! -d "${workpath}" ]
-                    then
-                        do_not_dir ${workpath}
-                    fi
-
-                    if [ -d "${modpath}" ] && [ -d "${controllerpath}" ] && [ -d "${workpath}" ]
-                    then
-                        do_crunch ${modpath} ${controllerpath} ${workpath}
-                    fi
-                done
-            else
-                controllername=${controllernames[${i}]}
-                controllerpath="${modpath}/${controllername}"
-
-                if [ ! -d "${controllerpath}" ]
-                then
-                    do_not_dir ${controllerpath}
-                fi
-
-                workpath="${controllerpath}/jobs"
-
-                if [ ! -d "${workpath}" ]
-                then
-                    do_not_dir ${workpath}
-                fi
-
-                if [ -d "${modpath}" ] && [ -d "${controllerpath}" ] && [ -d "${workpath}" ]
-                then
-                    do_crunch ${modpath} ${controllerpath} ${workpath}
-                fi
-            fi
-        done
-        ;;
     *)
         shift
-        sub_${subcommand} ${modules_dir} $@
+        sub_${subcommand} ${modules_dir} ${@}
         if [ $? = 127 ]; then
             echo "Error: '$subcommand' is not a known subcommand." >&2
             echo "       Run '$ProgName --help' for a list of known subcommands." >&2
